### ISSUE TITLE
JsCallInvoker on Android

### ISSUE THREAD

**Issue by VolkerLieber** [swittk/react-native-lua#1]
I had similar problems to what you described with calling the call invoker on Android. Maybe this can help you: [https://gist.github.com/VolkerLieber/fd7f5b95d8ec0b64c61f689d4c8a2d76](https://gist.github.com/VolkerLieber/fd7f5b95d8ec0b64c61f689d4c8a2d76)

**Comment by swittk** [comment]
Oh wow thanks a lot @VolkerLieber 

I'll be testing that out immediately once I get off my shift.

**Comment by VolkerLieber** [comment]
https://github.com/swittk/react-native-lua/commit/d43062632201ab214d3103d17447b8582c29dafc seems to implement the suggestion

**Comment by swittk** [comment]
Does it work for you? I only tried it on the Android Emulator since I don't daily-drive an Android phone.

**Comment by VolkerLieber** [comment]
Sorry for the late reply. I did not test your library on-device so far, but the library I'm currently working on uses the same "without fbjni" code and runs without problems on real Android devices.
