### ISSUE TITLE
Seems that concat token ".." is not supported 

### ISSUE THREAD

**Issue by TQCasey** [swittk/react-native-lua#2]
Seems that concat token ".." is not supported

**Comment by VolkerLieber** [comment]
Can you please provide an example?
The Lua version is `5.4.4`, which should support concatenation with `..` according to the reference manual ([https://www.lua.org/manual/5.4/manual.html](https://www.lua.org/manual/5.4/manual.html)):
```
3.4.6 – Concatenation
The string concatenation operator in Lua is denoted by two dots ('..'). 
If both operands are strings or numbers, then the numbers are converted to strings in a non-specified format
 (see [§3.4.3](https://www.lua.org/manual/5.4/manual.html#3.4.3)).
Otherwise, the __concat metamethod is called (see [§2.4](https://www.lua.org/manual/5.4/manual.html#2.4)).
```

**Comment by TQCasey** [comment]
sorry , seems my mistake, this can be closed now 

> Seems that concat token ".." is not supported
